# Generated by Django 5.0.4 on 2024-04-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='record',
            new_name='post',
        ),
    ]
